# import time
# from tasks import add
from tasks import data_extractor
# from celery.result import AsyncResult

# result = add.delay(1, 2)

# # the result that we get from the below is actually the task ID generated by Celery
# # print(result)

# # this code actually retrieves the value from the backend and displays the output. 
# # for the get function to work we should make sure that the backenc is explicitely mentioned. 
# # print(result.get())

data_extractor.delay()

# while True:
#     _result2 = AsyncResult(result.task_id)
#     # print(_result2)
#     status = _result2.status
#     print(status)
#     if 'SUCCESS' in status:
#         print('result after 5 sec wait {_result2}'.format(_result2=_result2.get()))
#         break
#     time.sleep(5)
